# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text=b'Latitude of the user', null=True)),
                ('longitude', models.FloatField(blank=True, help_text=b'Longitude of the user', null=True)),
                ('position_updated', models.DateTimeField(blank=True, help_text=b'The time the location was updated last', null=True)),
                ('location_precision', models.IntegerField(default=0, help_text=b'How accurate the location should be shown to the outside world.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geo_location',
            },
        ),
    ]
