# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text=b'The unique key for resetting password!', max_length=64, unique=True)),
                ('valid_until', models.DateTimeField(help_text=b'The time until this key is valid!')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
