# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position_updated',
        ),
    ]
