# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_removed_old_location_way'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrationkey',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='registrationkey',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegistrationKey',
        ),
    ]
