# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161013_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
