# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161014_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
