# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('core', '0009_lastseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toggles',
            fields=[
                ('toggle_name', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('activated_for', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
    ]
