# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Whether they are visible on the page.')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('useful_content', models.CharField(default='?', max_length=32)),
                ('uses_money', models.CharField(default='?', max_length=32)),
                ('automation', models.CharField(default='?', max_length=32)),
                ('project_plan', models.CharField(default='?', max_length=32)),
                ('implementation_oriented', models.CharField(default='?', max_length=32)),
                ('geographic_location', models.CharField(default='?', max_length=32)),
                ('rbe_network', models.CharField(default='?', max_length=32)),
                ('open_source', models.CharField(default='?', max_length=32)),
                ('system', models.CharField(default='?', max_length=32)),
                ('access', models.CharField(default='?', max_length=32)),
                ('resource', models.CharField(default='?', max_length=32)),
                ('participatory', models.CharField(default='?', max_length=32)),
                ('monetary', models.CharField(default='?', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', max_length=500)),
                ('value_system', models.TextField(blank=True, default='', max_length=500)),
                ('decision_making', models.TextField(blank=True, default='', max_length=500)),
                ('when_join', models.TextField(blank=True, default='', max_length=500)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Editor', 'Editor'), ('Follower', 'Follower')], max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(to='organizations.OrganizationTag'),
        ),
    ]
