# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text=b'The unique key for invite identification!', max_length=64, unique=True)),
                ('email', models.EmailField(default=b'', help_text=b'The email to send the invite too!', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitation_key',
            },
        ),
        migrations.AlterUniqueTogether(
            name='invitationkey',
            unique_together=set([('user', 'email')]),
        ),
    ]
