# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-10 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20161030_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='invited_by',
        ),
    ]
