# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now=True, help_text=b'The registration date of the event.')),
                ('related_clazz', models.CharField(blank=True, help_text=b'The name of the related clazz that holds the additional data.', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('unique_identifier', models.AutoField(auto_created=True, help_text=b'A unique id used to create a bar code and identify the item.', primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now=True, help_text=b'The registration date of the item.')),
                ('title', models.CharField(default=b'', help_text=b'A title that briefly describes the object.', max_length=60)),
                ('description', models.TextField(default=b'', help_text=b'A longer initial description if necessary to specify the object in more detail.', max_length=1000)),
                ('transport', models.BooleanField(default=True, help_text=b'State whether the object should be transported or stay locally.')),
                ('entered_by', models.ForeignKey(default=None, help_text=b'The user entering this object!', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='object_tags', to='core.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleObjectCommentEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Event')),
                ('comment_text', models.TextField(max_length=250)),
            ],
            bases=('inventory.event',),
        ),
        migrations.CreateModel(
            name='TagModificationLogEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Event')),
                ('added', models.BooleanField(default=True, help_text=b'Indicating if the tag was added or removed!')),
                ('tag_name', models.CharField(max_length=64)),
            ],
            bases=('inventory.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='object',
            field=models.ForeignKey(help_text=b'The object which the event happened to.', on_delete=django.db.models.deletion.CASCADE, to='inventory.Object'),
        ),
        migrations.AddField(
            model_name='event',
            name='triggered_user',
            field=models.ForeignKey(help_text=b'The user who triggered the event.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='event',
            index_together=set([('registration_date',)]),
        ),
    ]
