# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('unique_identifier', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('registration_date', models.DateField()),
                ('short_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.DateTimeField()),
                ('content', models.TextField(max_length=3000)),
                ('referenced_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Object')),
            ],
        ),
    ]
