# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, help_text=b'The message status - determines how the message is displayed')),
                ('subject', models.CharField(help_text=b'Subject of message', max_length=120)),
                ('message_text', models.CharField(help_text=b'The actual message text', max_length=1200)),
                ('sent_time', models.DateTimeField(auto_now=True, help_text=b'The datetime when the message was sent')),
                ('open_time', models.DateTimeField(default=None, help_text=b'The datetime when the message was read', null=True)),
                ('recipient', models.ForeignKey(help_text=b'The user who shall receive the message', on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(default=None, help_text=b'The reply_to field that indicates that the message was an reply to a previous one', null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Message')),
                ('sender', models.ForeignKey(help_text=b'The user who send the message', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
