# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_removed_unnecessary_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(blank=True, help_text=b'The datetime when the message was sent', null=True),
        ),
    ]
