# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-05 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_auto_20161118_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text=b'The actual message text', max_length=1200)),
                ('sent_time', models.DateTimeField(blank=True, help_text=b'The datetime when the message was sent', null=True)),
                ('author', models.ForeignKey(help_text=b'The user who send the message', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
