# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0018_hybridflow_and_clientattrs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associated', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCommunicationBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleClientCommunicationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('pending', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client')),
            ],
        ),
        migrations.AddField(
            model_name='associatedservice',
            name='sendout_day_period',
            field=models.IntegerField(default=28, help_text=b'The number of days until a client can send a simple message again.'),
        ),
    ]
